version: '3.2'

services:
  sftp:
    image: atmoz/sftp
    volumes:
      - jupyter-notebook:/home/${SFTP_USER}
    ports:
      - ${SFTP_PORT}:22
#    command: ${SFTP_USER}:${SFTP_PASSWORD}:::upload
    command: ${SFTP_USER}:${SFTP_PASSWORD}

  minio-s3:
    image: minio/minio:latest
    ports:
      - ${MINIO_PORT}:9000
    environment:
      - MINIO_ACCESS_KEY=${MINIO_ACCESS_KEY}
      - MINIO_SECRET_KEY=${MINIO_SECRET_KEY}
    command:
      server /data
    volumes:
      - s3-disk:/data

volumes:
  jupyter-notebook:
  s3-disk:


