version: '3'

services:
  postgresql:
    image: postgres:13
    ports:
      - ${MLFLOW_POSTGRES_PORT}:5432
    environment:
      POSTGRES_USER: ${MLFLOW_POSTGRES_USER}
      POSTGRES_PASSWORD: ${MLFLOW_POSTGRES_PASSWORD}
      POSTGRES_DB: mlflow-db
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8"
    restart: always
    volumes:
      - postgres_store_mlflow:/var/lib/postgresql/data

  waitfordb:
    image: dadarek/wait-for-dependencies
    depends_on:
      - postgresql
    command: postgresql:${MLFLOW_POSTGRES_PORT}

  mlflow_tracker:
    image: mlflow_tracker
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - postgresql
      - waitfordb
    environment:
      - MLFLOW_S3_ENDPOINT_URL=${MLFLOW_S3_ENDPOINT_URL}
      - AWS_ACCESS_KEY_ID=${MINIO_ACCESS_KEY}
      - AWS_SECRET_ACCESS_KEY=${MINIO_SECRET_KEY}
      - AWS_DEFAULT_REGION=${MINIO_REGION}
    ports:
      - ${MLFLOW_PORT}:${MLFLOW_PORT}
    entrypoint: mlflow server --host 0.0.0.0 --port ${MLFLOW_PORT} --backend-store-uri postgresql+psycopg2://${MLFLOW_POSTGRES_USER}:${MLFLOW_POSTGRES_PASSWORD}@postgresql:5432/mlflow-db --default-artifact-root s3://${MLFLOW_S3_BUCKET_NAME}/

volumes:
  postgres_store_mlflow:
